framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'
            fanout:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: order.fanout
                        type: fanout
                    queues:
                        order1.fanout:
                        order2.fanout:

            direct:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: sms.direct
                        type: direct
                    queues:
                        sms.service1:
                            binding_keys: ['sms1']
                        sms.service2:
                            binding_keys: ['sms2']

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
            'App\Message\Command\CreateOrder': fanout
            'App\Message\Command\SignUpSms': direct
